services:
  - type: web
    name: zoom-access-system
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: EMAIL
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: REDIS_URL
        fromService:
          name: zoom-redis
          type: redis

databases:
  - name: zoom-redis
    plan: free
    type: redis
