services:
  - type: web
    name: zoom-access-system
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: EMAIL
        sync: false
      - key: EMAIL_PASS
        sync: false
